[alembic]
script_location = alembic
file_template = %%(rev)s_%%(slug)s
prepend_sys_path = .
sqlalchemy.url = postgresql+psycopg2://postgres:postgres@localhost:5432/roadsentinel

[logging]
default_level = INFO
